---

- name: Ensure configuration directory exists
  ansible.builtin.file:
    path: /etc/redmine
    mode: 0755

- name: Ensure Redmine packages are installed
  ansible.builtin.apt:
    name: '{{ redmine_packages }}'

- name: Install ruby-dev if required
  ansible.builtin.apt:
    name: ruby-dev
  when: redmine_with_ruby_dev or not redmine_use_rvm_as_default

- name: Remove ruby-dev if not required
  ansible.builtin.apt:
    name: ruby-dev
    purge: true
  when:
    - not redmine_with_ruby_dev
    - redmine_use_rvm_as_default
