---
- name: "{{ ansible_system }}: Get RPM or APT package facts."
  ansible.builtin.package_facts:
    manager: "auto"
  tags:
    - get-package-facts

- name: "{{ ansible_system }}: Populate service facts."
  ansible.builtin.service_facts:

- name: "{{ ansible_system }}: Import Legacy agent tasks."
  ansible.builtin.include_tasks: "legacy.yml"
  when: |
    checkmk_agent_prep_legacy | bool
    and ansible_facts.packages['systemd'][0]['version'] | regex_search('\d{1,}') | int < 220

- name: "{{ ansible_system }}: Download Vanilla agent."
  ansible.builtin.get_url:
    url: "{{ checkmk_agent_agent.url.cre }}"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    dest: "{{ checkmk_agent_agent.file.cre }}"
    mode: '0640'
  when: checkmk_agent_edition | lower == "cre"
  register: result
  retries: 3
  delay: 10
  until: "not result.failed | bool"
  delegate_to: "{{ checkmk_agent_delegate_download }}"
  tags:
    - download-package

- name: "{{ ansible_os_family }}: Run OS Family specific tasks."
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  tags:
    - include-os-family-tasks

- name: "Create host on server."
  checkmk.general.host:
    server_url: "{{ checkmk_agent_protocol }}://{{ checkmk_agent_server }}:{{ checkmk_agent_port }}/"
    site: "{{ checkmk_agent_site }}"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    automation_user: "{{ checkmk_agent_user }}"
    automation_secret: "{{ checkmk_agent_auth }}"
    folder: "{{ checkmk_agent_folder | default(omit) }}"
    name: "{{ checkmk_agent_host_name }}"
    attributes: "{{ checkmk_agent_host_attributes }}"
    state: "present"
  become: false
  register: checkmk_agent_create_result
  failed_when: |
    (checkmk_agent_create_result.failed == true) and
    ("The host is already part of the specified target folder" not in checkmk_agent_create_result.msg)
  delegate_to: "{{ checkmk_agent_delegate_api_calls }}"
  when: checkmk_agent_add_host | bool
  notify: "activate changes"

- name: "{{ ansible_system }}: Check for Agent Updater Binary."
  ansible.builtin.stat:
    path: /usr/bin/cmk-update-agent
  register: checkmk_agent_updater_binary

- name: "{{ ansible_system }}: Check for Agent Controller Binary."
  ansible.builtin.stat:
    path: /usr/bin/cmk-agent-ctl
  register: checkmk_agent_controller_binary

- name: "{{ ansible_system }}: Register Agent for automatic Updates using User Password."  # noqa no-changed-when
  become: true
  ansible.builtin.shell: |
    cmk-update-agent register -H {{ checkmk_agent_host_name }} \
    -s {{ checkmk_agent_registration_server }} -i {{ checkmk_agent_registration_site }} -p {{ checkmk_agent_protocol }} \
    -U {{ checkmk_agent_user }} -P {{ checkmk_agent_auth }}
  register: checkmk_agent_update_state
  when: |
    checkmk_agent_edition | lower != "cre"
    and checkmk_agent_updater_binary.stat.exists | bool
    and checkmk_agent_update | bool
    and (checkmk_agent_pass is defined and checkmk_agent_pass | length)
    and (checkmk_agent_secret is not defined)

- name: "{{ ansible_system }}: Register Agent for automatic Updates using Automation Secret."  # noqa no-changed-when
  become: true
  ansible.builtin.shell: |
    cmk-update-agent register -H {{ checkmk_agent_host_name }} \
    -s {{ checkmk_agent_registration_server }} -i {{ checkmk_agent_registration_site }} -p {{ checkmk_agent_protocol }} \
    -U {{ checkmk_agent_user }} -S {{ checkmk_agent_auth }}
  register: checkmk_agent_update_state
  when: |
    checkmk_agent_edition | lower != "cre"
    and checkmk_agent_updater_binary.stat.exists | bool
    and checkmk_agent_update | bool
    and (checkmk_agent_secret is defined and checkmk_agent_secret | length)

- name: "{{ ansible_system }}: Register Agent for TLS."  # noqa no-changed-when
  become: true
  ansible.builtin.shell: |
    cmk-agent-ctl register -H {{ checkmk_agent_host_name }} \
    -s {{ checkmk_agent_registration_server }} -i {{ checkmk_agent_registration_site }} \
    -U {{ checkmk_agent_user }} -P {{ checkmk_agent_auth }} --trust-cert
  register: checkmk_agent_tls_state
  when: |
    checkmk_agent_controller_binary.stat.exists | bool
    and checkmk_agent_tls | bool
    and (checkmk_agent_auth is defined and checkmk_agent_auth | length)

- name: "Verify Checkmk Agent Port is open."
  ansible.builtin.wait_for:
    port: 6556
    timeout: 60
