# Copyright 2022 IDRIS / jupyter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# This playbook deploys JupyterHub and monitoring stack.

- name: Gather facts from jupyterhub hosts
  hosts: all
  gather_facts: yes
  tags:
    - always

- name: Validate environment
  hosts: all
  gather_facts: no
  roles:
    - validation
  tags:
    - always
    
- name: Preflights
  hosts: localhost
  gather_facts: no
  roles:
    - preflights
  tags:
    - always

- name: Include conda role
  hosts: all
  gather_facts: no
  roles:
    - evandam.conda
  tags:
    - always
  
- name: Run common tasks
  hosts: all
  gather_facts: no
  pre_tasks:
    - include_vars: config.yml
  roles:
    - setup_hosts
  tags:
    - prerequisites
    - molecule-idempotence-notest
  
- name: Setup jupyterhub environment
  hosts: jupyterhub
  gather_facts: no
  pre_tasks:
    - include_vars: config.yml
  roles:
    - setup_jupyterhub
  tags:
    - jupyterhub

- name: Setup nginx reverse proxy
  hosts: nginx
  gather_facts: no
  pre_tasks:
    - include_vars: config.yml
  roles:
    - setup_nginx
  tags:
    - nginx

- name: Setup node_exporter
  hosts: node_exporter
  gather_facts: no
  pre_tasks:
    - include_vars: config.yml
  roles:
    - role: setup_node_exporter
      when: install_mon_stack
    - role: cloudalchemy.node_exporter
      when: install_mon_stack
      tags:
        - molecule-idempotence-notest
  tags:
    - node_exporter
    - monitoring
  
- name: Setup prometheus
  hosts: prometheus
  gather_facts: no
  pre_tasks:
    - include_vars: config.yml
  roles:
    - role: setup_prometheus
      when: install_mon_stack
    - role: cloudalchemy.prometheus
      when: install_mon_stack
      tags:
        - molecule-idempotence-notest
  tags:
    - prometheus
    - monitoring
    
- name: Setup promtail
  hosts: promtail
  gather_facts: no
  pre_tasks:
    - include_vars: config.yml
  roles:
    - role: setup_promtail
      when: install_mon_stack
    - role: patrickjahns.promtail
      when: install_mon_stack
      tags:
        - molecule-idempotence-notest
  tags:
    - promtail
    - monitoring
  
- name: Setup grafana loki
  hosts: loki
  gather_facts: no
  pre_tasks:
    - include_vars: config.yml
  roles:
    - role: setup_loki
      when: install_mon_stack
  tags:
    - loki
    - monitoring

- name: Setup grafana
  hosts: grafana
  gather_facts: no
  pre_tasks:
    - include_vars: config.yml
  roles:
    - role: setup_grafana
      when: install_mon_stack
    - role: cloudalchemy.grafana
      when: install_mon_stack
      tags:
        - molecule-idempotence-notest
  tags:
    - grafana
    - monitoring
  
- name: Setup logrotate
  hosts: all
  gather_facts: no
  pre_tasks:
    - include_vars: config.yml
  roles:
    - setup_logrotate
  tags:
    - logrotate
