---

- name: check the configuration of the business process
  assert:
    that:
      - businessprocess.title | length > 0
      - businessprocess.owner | length > 0
      - businessprocess.menu in (True, False)
      - businessprocess.statetype in ('soft', 'hard')
      - businessprocess.nodes | length > 0

- name: check the configuration of the nodes
  assert:
    that:
      - node.name | length > 0
      - node.displayname | length > 0
      - node.operator | length > 0
      - node.visible in (True, False)
      - node.checks | length > 0
  loop: "{{ businessprocess.nodes }}"
  loop_control:
    loop_var: node

- name: perform node configuration checks
  include_tasks: configuration_checks_node.yml
  loop: "{{ businessprocess.nodes }}"
  loop_control:
    loop_var: node
