---

- name: Ensure apt keys
  become: true
  ansible.builtin.apt_key:
    id: "{{ apt_key.id }}"
    url: "{{ apt_key.url }}"
  notify: ensure apt cache
  loop: "{{ apt_keys }}"
  loop_control:
    loop_var: apt_key
