---
# tasks file to add additonal repositories to the apt package manager
- name: Apt | add_repos
  become: true
  block:
    - name: Apt | add_repos | Add public keys
      ansible.builtin.apt_key:
        url: "{{ item.ppa_key }}"
      loop: "{{ add_repos | default([]) }}"
      when: item.ppa_key is defined

    - name: Apt | Add additional repos
      ansible.builtin.apt_repository:
        repo: "{{ item.ppa }}"
      loop: "{{ add_repos | default([]) }}"
      when: item.ppa is defined
