---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: "Installing packages"
      yum:
        name: "{{ item }}"
      with_items:
        - net-tools
        - which
        - libselinux-python
      register: installation_dependencies
      when: ansible_distribution == 'CentOS'

    - name: "Installing which on NON-CentOS"
      apt:
        name: "{{ item }}"
      with_items:
        - net-tools
      when: ansible_distribution != 'CentOS'

    - name: "Configure SUDO."
      lineinfile:
        dest: /etc/sudoers
        line: "Defaults    !requiretty"

    - name: "Make sure the docs are installed."
      lineinfile:
        dest: /etc/yum.conf
        line: "tsflags=nodocs"

  roles:
    - role: geerlingguy.postgresql
      when: inventory_hostname in groups['postgresql']
    - role: geerlingguy.mysql
      when: inventory_hostname in groups['mysql']
