---
name: CI

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main
