---
- name: set tor socks port
  ansible.builtin.lineinfile:
    path: /etc/tor/torrc
    regexp: "^#?SocksPort"
    line: "SocksPort {{ tor_socks_port }}"
  notify: restart tor service

- name: disable dangerous exit nodes
  ansible.builtin.lineinfile:
    path: /etc/tor/torrc
    regexp: "^#?ExcludeNodes"
    line: "ExcludeNodes {{ tor_exclude_nodes |map('regex_replace','^(.*)$','{\\1}') |join(',') }}"
  notify: restart tor service

- name: disable hourly "tor has been idle" reports
  ansible.builtin.lineinfile:
    path: /etc/tor/torrc
    regexp: "^Log\\s"
    line: "Log warn syslog"
  notify: restart tor service

- name: configure tor log compression
  ansible.builtin.replace:
    path: /etc/logrotate.d/tor
    regexp: "{{ lookbehind }}(compress|delaycompress)"
    replace: "{{ commentout }}\\1"
  vars:
    lookbehind: "{{ lin_compress_logs |bool |ternary('(?:#\\s*)','(?<!#)') }}"
    commentout: "{{ lin_compress_logs |bool |ternary('','#') }}"
  when: lin_compress_logs is not none
...
