---
- name: directory for mongodb service drop-in
  ansible.builtin.file:
    path: /etc/systemd/system/mongod.service.d
    mode: 0755

- name: setup mongodb service quotas
  ansible.builtin.template:
    src: service-quotas.conf
    dest: /etc/systemd/system/mongod.service.d/quotas.conf
    mode: 0644
  notify:
    - reload systemd daemon
    - restart mongodb service

- name: enable mongodb service
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    daemon_reload: true


- name: open mongodb port in ufw
  community.general.ufw:
    rule: allow
    port: "{{ mongodb_port |string }}"
    proto: tcp
  no_log: "{{ hide_secrets |bool }}"
  when: lin_firewall == 'ufw'

- name: open mongodb port in ferm
  ivansible.base.ferm_port:
    port: "{{ mongodb_port }}"
    proto: tcp
    comment: mongodb
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'
...
