---
- name: add package cloud signing key
  ansible.builtin.apt_key:
    url: https://packagecloud.io/netdata/netdata/gpgkey

- name: add package cloud repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ lin_apt_arch }}] {{ url }} {{ codename }} main"
    filename: netdata
    mode: 0644
  vars:
    url: https://packagecloud.io/netdata/netdata/ubuntu/
    codename: "{{ ansible_lsb.codename }}"

- name: install netdata package
  ansible.builtin.apt:
    name: netdata
  notify: restart netdata service

- name: silence systemd warning on xenial
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/netdata.service
    line: ProtectControlGroups=true
  notify: reload systemd daemon
  when: ansible_lsb.codename == 'xenial'

- name: configure netdata
  ansible.builtin.template:
    src: netdata/netdata.conf
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: 0644
  notify: restart netdata service
  vars:
    plugin_core: 'yes'
    plugin_extra: "{{ srv_netdata_extra_plugins |default(false) |bool |ternary('no','yes') }}"
    plugin_big: "{{ srv_netdata_lowmem |default(false) |bool |ternary('no','yes') }}"
    plugin_dir: "{{ have_dirs |ternary('yes','no') }}"
    have_dirs: "{{ have_disk_dirs or have_rclone_dirs }}"
    have_disk_dirs: "{{ srv_netdata_disk_dirs |d([],true) |length > 0 }}"
    have_rclone_dirs: "{{ srv_netdata_rclone_dirs |d([],true) |length > 0 }}"

- name: enable netdata service
  ansible.builtin.systemd:
    name: netdata
    enabled: true

- name: open internal netdata port in ferm
  ivansible.base.ferm_port:
    port: 19999
    proto: tcp
    zone: internal
    comment: netdata
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'
...
