---
- name: Prepare
  hosts: all
  tasks:
    - name: Install requirements for tests
      ansible.builtin.yum:
        name:
          - sudo
          - iproute
          - python3-lxml

    - name: "Retrieve assets server from env"
      ansible.builtin.set_fact:
        assets_server: "{{ lookup('env','MIDDLEWARE_DOWNLOAD_RELEASE_SERVER_URL') }}"

    - name: "Download and deploy jdg zips from {{ assets_server }}" # noqa risky-file-permissions this goes on controller with local user account
      ansible.builtin.get_url:
        url: "{{ asset }}"
        dest: "{{ lookup('env', 'PWD') }}"
        validate_certs: no
      delegate_to: localhost
      loop:
         - "{{ assets_server }}/datagrid/8.4.0/redhat-datagrid-8.4.0-server.zip"
      loop_control:
        loop_var: asset
      when:
        - assets_server is defined
        - assets_server | length > 0
