# The MIT License
#  
# Copyright 2021 Brian Reid
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

- hosts: localhost
  gather_facts: no
  tasks:
    # Note depending on whether you install this from ansible galaxy or locally the module name may need to be changed.
    # ryan_gordon1.cloud_pak_for_security.<module_name> or <module_name>

    - name: Query one field
      cp4s_query_incidents:
        conditions: '["name","splunk","contains"]'
      register: matched_cases

    - name: Query multiple fields
      cp4s_query_incidents:
        conditions: '[["name","with","contains"],["name","space","contains"]]'
        multiple_fields: True
      register: matched_cases
    # - name: Test creation of a DNS Name artifact
    #   cp4s_create_artifact:
    #     type: "DNS Name"
    #     value: "google.com"
    # - name: Test closure of a Case
    #   cp4s_create_note:
    #     case_id: '{{ created_case.case.id }}'
    #     text: "Hello SOC Team"