---
- name: Prepare
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache
      package:
        update_cache: true
    - name: Ensure ACL package
      package:
        name: acl
    - name: Ensure /proc file system utilities
      package:
        name: procps
    - name: Ensure auth.log file is present
      copy:
        dest: /var/log/auth.log
        content: ""
        force: false
        mode: 0644
      when: ansible_distribution == 'Debian'
