---
- name: Create command and service template for Azure oauth token
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/telekom_mms.icinga_director.icinga:
      url: "{{ icinga_url }}"
      url_username: "{{ icinga_user }}"
      url_password: "{{ icinga_pass }}"
      force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
  tasks:
    - name: Create command Azure oauth token
      telekom_mms.icinga_director.icinga_command:
        object_name: azure_oauth_token
        command: "azure_oauth_token.py"
        arguments:
          (no key):
            order: 1
            required: true
            skip_key: true
            value: $tenant_id$
          (no key.1):
            order: 2
            required: true
            skip_key: true
            value: $client_id$
          (no key.2):
            order: 3
            required: true
            skip_key: true
            value: $client_secret$
          (no key.3):
            order: 4
            required: true
            skip_key: true
            value: $scope$
    - name: Create service template for Azure oauth token
      telekom_mms.icinga_director.icinga_service_template:
        object_name: "azure_oauth_token"
        check_command: "azure_oauth_token"
        check_interval: 50m
