---
- name: Apt - ensure apt keyrings directory
  file:
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: '0755'

- name: Apt - add repository key
  ansible.builtin.get_url:
    url: "{{ icinga_repo_apt_key }}"
    dest: "{{ icinga_repo_apt_keyring }}"
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Apt - add Icinga repository (stable)
  become: yes
  apt_repository:
    filename: /etc/apt/sources.list.d/icinga
    repo: "{{ icinga_repo_apt_stable_deb }}"
- name: Apt - add Icinga repository (testing)
  become: yes
  apt_repository:
    filename: /etc/apt/sources.list.d/icinga
    repo: "{{ icinga_repo_apt_testing_deb }}"
- name: Apt - add Icinga repository (snapshot)
  become: yes
  apt_repository:
    filename: /etc/apt/sources.list.d/icinga
    repo: "{{ icinga_repo_apt_snapshot_deb }}"
