- name: Create mms-standards
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/telekom_mms.icinga_director.icinga:
      url: "{{ icinga_url }}"
      url_username: "{{ icinga_user }}"
      url_password: "{{ icinga_pass }}"
      force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
  tasks:
    - name: Create timeperiod for mms-standard-service
      telekom_mms.icinga_director.icinga_timeperiod:
        state: present
        object_name: 24/7
        ranges:
          monday: "00:00-24:00"
          tuesday: "00:00-24:00"
          wednesday: "00:00-24:00"
          thursday: "00:00-24:00"
          friday: "00:00-24:00"
          saturday: "00:00-24:00"
          sunday: "00:00-24:00"

    - name: Create service template for mms-standard-service
      telekom_mms.icinga_director.icinga_service_template:
        state: present
        object_name: mms-standard-service
        max_check_attempts: "3"
        check_period: "24/7"
        check_interval: "2m"
        retry_interval: "1m"
        enable_notifications: true
        enable_active_checks: true
        enable_passive_checks: false
        enable_event_handler: false
        enable_perfdata: true
        volatile: false
