---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.git
    - role: geerlingguy.dotfiles
