---
- hosts: all

  tasks:
    - name: Update the apt cache so we can install ufw.
      apt: cache_valid_time=600

    - name: Install ufw so we can disable it in the playbook.
      apt: name=ufw

# Includes test.
- import_playbook: ../includes/provisioning/playbook.yml
