---

- name: Groups > Groups configuration
  ansible.builtin.group:
    name: "{{ (item) if (item is string) else (item.group) }}"
    system: "{{ item.system | default(omit) }}"
    gid: "{{ item.gid | default(omit) }}"
  loop: "{{
    manala_accounts_groups
      | flatten
      | manala.roles.staten
  }}"
